global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: apiscloud-dev

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'apiscloud-services'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:9101']
        labels: { service: 'gateway' }
      - targets: ['host.docker.internal:9103']
        labels: { service: 'ingest' }
      - targets: ['host.docker.internal:9104']
        labels: { service: 'data-writer' }
      - targets: ['host.docker.internal:9105']
        labels: { service: 'dispatch-core' }
      - targets: ['host.docker.internal:9107']
        labels: { service: 'simulator' }
      - targets: ['host.docker.internal:9108']
        labels: { service: 'aggregator' }
